/*
	Mod Support RwF Localisation
	Credits: ChimpanG
*/

-----------------------------------------------
-- Types
-----------------------------------------------

INSERT OR REPLACE INTO LocalizedText
		(Tag,																			Language,	Text						)
VALUES	("LOC_CIVILIZATION_CVS_SONGHAI_DESCRIPTION_JFD_CIVILIZATION",					"en_US",	"Songhai Empire"			),

		("LOC_GOVERNMENT_JFD_CHIEFDOM_LEADER_TITLE_CVS_SONGHAI",						"en_US",	"Nganga"					),
		("LOC_GOVERNMENT_JFD_CHIEFDOM_LEADER_TITLE_CVS_SONGHAI_FEMININE",				"en_US",	"Nganga"					),
		("LOC_GOVERNMENT_JFD_HORDE_LEADER_TITLE_CVS_SONGHAI",							"en_US",	"War Chief"					),
		("LOC_GOVERNMENT_JFD_HORDE_LEADER_TITLE_CVS_SONGHAI_FEMININE",					"en_US",	"War Chieftess"				),
		("LOC_GOVERNMENT_JFD_POLIS_LEADER_TITLE_CVS_SONGHAI",							"en_US",	"Elder"						),
		("LOC_GOVERNMENT_JFD_POLIS_LEADER_TITLE_CVS_SONGHAI_FEMININE",					"en_US",	"Elderess"					),

		("LOC_GOVERNMENT_JFD_AUTOCRACY_LEADER_TITLE_CVS_SONGHAI",						"en_US",	"Warlordf"					),
		("LOC_GOVERNMENT_JFD_AUTOCRACY_LEADER_TITLE_CVS_SONGHAI_FEMININE",				"en_US",	"Warlord"					),
		("LOC_GOVERNMENT_JFD_OLIGARCHY_LEADER_TITLE_CVS_SONGHAI",						"en_US",	"Speaker"					),
		("LOC_GOVERNMENT_JFD_OLIGARCHY_LEADER_TITLE_CVS_SONGHAI_FEMININE",				"en_US",	"Speaker"					),
		("LOC_GOVERNMENT_JFD_CLASSICAL_DEMOCRACY_LEADER_TITLE_CVS_SONGHAI",				"en_US",	"Mwene"						),
		("LOC_GOVERNMENT_JFD_CLASSICAL_DEMOCRACY_LEADER_TITLE_CVS_SONGHAI_FEMININE",	"en_US",	"Mwene"						),

		("LOC_GOVERNMENT_JFD_FEUDAL_MONARCHY_LEADER_TITLE_CVS_SONGHAI",					"en_US",	"Sii"						),
		("LOC_GOVERNMENT_JFD_FEUDAL_MONARCHY_LEADER_TITLE_CVS_SONGHAI_FEMININE",		"en_US",	"Sii"						),
		("LOC_GOVERNMENT_JFD_MERCHANT_REPUBLIC_LEADER_TITLE_CVS_SONGHAI",				"en_US",	"Mwene"						),
		("LOC_GOVERNMENT_JFD_MERCHANT_REPUBLIC_LEADER_TITLE_CVS_SONGHAI_FEMININE",		"en_US",	"Mwene"						),
		("LOC_GOVERNMENT_JFD_GOVERNMENT_THEOCRACY_LEADER_TITLE_CVS_SONGHAI",			"en_US",	"Speaker"					),
		("LOC_GOVERNMENT_JFD_GOVERNMENT_THEOCRACY_LEADER_TITLE_CVS_SONGHAI_FEMININE",	"en_US",	"Speaker"					),

		("LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_CVS_SONGHAI",						"en_US",	"Sii"						),
		("LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_CVS_SONGHAI_FEMININE",				"en_US",	"Sii"						),
		("LOC_GOVERNMENT_JFD_NOBLE_REPUBLIC_LEADER_TITLE_CVS_SONGHAI",					"en_US",	"Mwene"						),
		("LOC_GOVERNMENT_JFD_NOBLE_REPUBLIC_LEADER_TITLE_CVS_SONGHAI_FEMININE",			"en_US",	"Mwene"						),
		
		("LOC_GOVERNMENT_JFD_LIBERAL_DEMOCRACY_LEADER_TITLE_CVS_SONGHAI",				"en_US",	"President"					),
		("LOC_GOVERNMENT_JFD_LIBERAL_DEMOCRACY_LEADER_TITLE_CVS_SONGHAI_FEMININE",		"en_US",	"President"					),
		("LOC_GOVERNMENT_JFD_PEOPLES_REPUBLIC_LEADER_TITLE_CVS_SONGHAI",				"en_US",	"General Secretary"			),
		("LOC_GOVERNMENT_JFD_PEOPLES_REPUBLIC_LEADER_TITLE_CVS_SONGHAI_FEMININE",		"en_US",	"General Secretary"			),
		("LOC_GOVERNMENT_JFD_MILITARY_GUARDIANSHIP_LEADER_TITLE_CVS_SONGHAI",			"en_US",	"Warlord"					),
		("LOC_GOVERNMENT_JFD_MILITARY_GUARDIANSHIP_LEADER_TITLE_CVS_SONGHAI_FEMININE",	"en_US",	"Warlord"					),
		
		("LOC_GOVERNMENT_JFD_EMPIRE_LEADER_TITLE_CVS_SONGHAI",							"en_US",	"Sii"						),
		("LOC_GOVERNMENT_JFD_EMPIRE_LEADER_TITLE_CVS_SONGHAI_FEMININE",					"en_US",	"Sii"						);
