/*
	Mod Support RwF
	Credits: ChimpanG
*/

-----------------------------------------------
-- JFD'S RULE WITH FAITH
-----------------------------------------------

CREATE TABLE IF NOT EXISTS 
	Civilization_Titles (
	CivilizationType		TEXT	DEFAULT NULL,
	GovernmentType			TEXT	DEFAULT NULL,
	LeaderTitle				TEXT	DEFAULT NULL,
	PolicyType				TEXT	DEFAULT NULL
	);

CREATE TABLE IF NOT EXISTS 
	Leader_Titles (
	LeaderType	TEXT 			 		DEFAULT NULL,
	GovernmentType			TEXT		DEFAULT NULL,
	LeaderTitle				TEXT		DEFAULT NULL,
	PolicyType  			TEXT 		DEFAULT NULL,
	UseFeminine				BOOLEAN		DEFAULT 0,
	TitleIsFullName			BOOLEAN		DEFAULT 0
	);
	
INSERT INTO Civilization_Titles
		(CivilizationType, 				GovernmentType, 							PolicyType,				LeaderTitle																		)
VALUES	('CIVILIZATION_CVS_SONGHAI',	'GOVERNMENT_CHIEFDOM',						NULL,					'LOC_GOVERNMENT_JFD_CHIEFDOM_LEADER_TITLE_CVS_SONGHAI'							), -- Chiefdom
		('CIVILIZATION_CVS_SONGHAI',	'GOVERNMENT_JFD_HORDE',						NULL,					'LOC_GOVERNMENT_JFD_HORDE_LEADER_TITLE_CVS_SONGHAI'								), -- Horde
		('CIVILIZATION_CVS_SONGHAI',	'GOVERNMENT_JFD_POLIS',						NULL,					'LOC_GOVERNMENT_JFD_POLIS_LEADER_TITLE_CVS_SONGHAI'								), -- Polis
		('CIVILIZATION_CVS_SONGHAI',	'GOVERNMENT_AUTOCRACY',						NULL,					'LOC_GOVERNMENT_JFD_AUTOCRACY_LEADER_TITLE_CVS_SONGHAI'							), -- Autocracy
		('CIVILIZATION_CVS_SONGHAI',	'GOVERNMENT_OLIGARCHY',						NULL,					'LOC_GOVERNMENT_JFD_OLIGARCHY_LEADER_TITLE_CVS_SONGHAI'							), -- Oligarchy
		('CIVILIZATION_CVS_SONGHAI',	'GOVERNMENT_CLASSICAL_REPUBLIC',			NULL,					'LOC_GOVERNMENT_JFD_CLASSICAL_DEMOCRACY_LEADER_TITLE_CVS_SONGHAI'				), -- Classical Democracy
		('CIVILIZATION_CVS_SONGHAI',	'GOVERNMENT_MONARCHY',						NULL,					'LOC_GOVERNMENT_JFD_FEUDAL_MONARCHY_LEADER_TITLE_CVS_SONGHAI'					), -- Feudal Monarchy
		('CIVILIZATION_CVS_SONGHAI',	'GOVERNMENT_MERCHANT_REPUBLIC',				NULL,					'LOC_GOVERNMENT_JFD_MERCHANT_REPUBLIC_LEADER_TITLE_CVS_SONGHAI'					), -- Merchant Republic
		('CIVILIZATION_CVS_SONGHAI',	'GOVERNMENT_THEOCRACY',						NULL,					'LOC_GOVERNMENT_JFD_GOVERNMENT_THEOCRACY_LEADER_TITLE_CVS_SONGHAI'				), -- Theocracy
		('CIVILIZATION_CVS_SONGHAI',	'GOVERNMENT_JFD_ABSOLUTE_MONARCHY',			NULL,					'LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_CVS_SONGHAI'							), -- Absolute Monarchy
		('CIVILIZATION_CVS_SONGHAI',	'GOVERNMENT_JFD_CONSTITUTIONAL_MONARCHY',	NULL,					'LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_CVS_SONGHAI'							), -- Constitutional Monarchy
		('CIVILIZATION_CVS_SONGHAI',	'GOVERNMENT_JFD_NOBLE_REPUBLIC',			NULL,					'LOC_GOVERNMENT_JFD_OLIGARCHY_LEADER_TITLE_CVS_SONGHAI'							), -- Noble Republic
		('CIVILIZATION_CVS_SONGHAI',	'GOVERNMENT_DEMOCRACY',						NULL,					'LOC_GOVERNMENT_JFD_LIBERAL_DEMOCRACY_LEADER_TITLE_CVS_SONGHAI'					), -- Liberal Democracy
		('CIVILIZATION_CVS_SONGHAI',	'GOVERNMENT_COMMUNISM',						NULL,					'LOC_GOVERNMENT_JFD_PEOPLES_REPUBLIC_LEADER_TITLE_CVS_SONGHAI'					), -- People's Republic
		('CIVILIZATION_CVS_SONGHAI',	'GOVERNMENT_FASCISM',						NULL,					'LOC_GOVERNMENT_JFD_MILITARY_GUARDIANSHIP_LEADER_TITLE_CVS_SONGHAI'				), -- Military Guardianship
		('CIVILIZATION_CVS_SONGHAI',	NULL,										'POLICY_JFD_EMPIRE',	'LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_CVS_SONGHAI'							), -- Empire
		
		('CIVILIZATION_CVS_SONGHAI',	'GOVERNMENT_CHIEFDOM',						NULL,					'LOC_GOVERNMENT_JFD_CHIEFDOM_LEADER_TITLE_CVS_SONGHAI_FEMININE'					), -- Chiefdom
		('CIVILIZATION_CVS_SONGHAI',	'GOVERNMENT_JFD_HORDE',						NULL,					'LOC_GOVERNMENT_JFD_HORDE_LEADER_TITLE_CVS_SONGHAI_FEMININE'					), -- Horde
		('CIVILIZATION_CVS_SONGHAI',	'GOVERNMENT_JFD_POLIS',						NULL,					'LOC_GOVERNMENT_JFD_POLIS_LEADER_TITLE_CVS_SONGHAI_FEMININE'					), -- Polis
		('CIVILIZATION_CVS_SONGHAI',	'GOVERNMENT_AUTOCRACY',						NULL,					'LOC_GOVERNMENT_JFD_AUTOCRACY_LEADER_TITLE_CVS_SONGHAI_FEMININE'				), -- Autocracy
		('CIVILIZATION_CVS_SONGHAI',	'GOVERNMENT_OLIGARCHY',						NULL,					'LOC_GOVERNMENT_JFD_OLIGARCHY_LEADER_TITLE_CVS_SONGHAI_FEMININE'				), -- Oligarchy
		('CIVILIZATION_CVS_SONGHAI',	'GOVERNMENT_CLASSICAL_REPUBLIC',			NULL,					'LOC_GOVERNMENT_JFD_CLASSICAL_DEMOCRACY_LEADER_TITLE_CVS_SONGHAI_FEMININE'		), -- Classical Democracy
		('CIVILIZATION_CVS_SONGHAI',	'GOVERNMENT_MONARCHY',						NULL,					'LOC_GOVERNMENT_JFD_FEUDAL_MONARCHY_LEADER_TITLE_CVS_SONGHAI_FEMININE'			), -- Feudal Monarchy
		('CIVILIZATION_CVS_SONGHAI',	'GOVERNMENT_MERCHANT_REPUBLIC',				NULL,					'LOC_GOVERNMENT_JFD_MERCHANT_REPUBLIC_LEADER_TITLE_CVS_SONGHAI_FEMININE'		), -- Merchant Republic
		('CIVILIZATION_CVS_SONGHAI',	'GOVERNMENT_THEOCRACY',						NULL,					'LOC_GOVERNMENT_JFD_GOVERNMENT_THEOCRACY_LEADER_TITLE_CVS_SONGHAI_FEMININE'		), -- Theocracy
		('CIVILIZATION_CVS_SONGHAI',	'GOVERNMENT_JFD_ABSOLUTE_MONARCHY',			NULL,					'LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_CVS_SONGHAI_FEMININE'					), -- Absolute Monarchy
		('CIVILIZATION_CVS_SONGHAI',	'GOVERNMENT_JFD_CONSTITUTIONAL_MONARCHY',	NULL,					'LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_CVS_SONGHAI_FEMININE'					), -- Constitutional Monarchy
		('CIVILIZATION_CVS_SONGHAI',	'GOVERNMENT_JFD_NOBLE_REPUBLIC',			NULL,					'LOC_GOVERNMENT_JFD_OLIGARCHY_LEADER_TITLE_CVS_SONGHAI_FEMININE'				), -- Noble Republic
		('CIVILIZATION_CVS_SONGHAI',	'GOVERNMENT_DEMOCRACY',						NULL,					'LOC_GOVERNMENT_JFD_LIBERAL_DEMOCRACY_LEADER_TITLE_CVS_SONGHAI_FEMININE'		), -- Liberal Democracy
		('CIVILIZATION_CVS_SONGHAI',	'GOVERNMENT_COMMUNISM',						NULL,					'LOC_GOVERNMENT_JFD_PEOPLES_REPUBLIC_LEADER_TITLE_CVS_SONGHAI_FEMININE'			), -- People's Republic
		('CIVILIZATION_CVS_SONGHAI',	'GOVERNMENT_FASCISM',						NULL,					'LOC_GOVERNMENT_JFD_MILITARY_GUARDIANSHIP_LEADER_TITLE_CVS_SONGHAI_FEMININE'	), -- Military Guardianship
		('CIVILIZATION_CVS_SONGHAI',	NULL,										'POLICY_JFD_EMPIRE',	'LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_CVS_SONGHAI_FEMININE'					); -- Empire

DELETE FROM Civilization_Titles WHERE CivilizationType = 'CIVILIZATION_CVS_SONGHAI' AND GovernmentType IS NOT NULL AND GovernmentType NOT IN (SELECT GovernmentType FROM Governments);
DELETE FROM Civilization_Titles WHERE CivilizationType = 'CIVILIZATION_CVS_SONGHAI' AND PolicyType IS NOT NULL AND PolicyType NOT IN (SELECT PolicyType FROM Policies);
